version: "3.2"

services:
  vpn:
    image: dperson/openvpn-client:latest
    container_name: vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - label:disable
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - vpn-network
    dns:
      - 84.200.69.80
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - 8191:8191 # Flaresolver
      - 8586:8586 # WebUI qbittorrent
      - 9117:9117 # WebUI jackett
      - 7878:7878 # WebUI radarr
      - 8989:8989 # WebUI sonarr
      - 5055:5055 # WebUI overseer
      - 8080:8080 # WebUI rutorrent
      - 32400:32400 #Plex
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${RACINE}/vpn/config:/vpn
      - ${RACINE}/vpn/scripts:/scripts
    command: '-f "" -r 192.168.0.0/24'
    healthcheck:
      test: ["CMD", "curl", "-Ss", "ifconfig.me"]
      interval: 60s
      timeout: 15s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8586
    volumes:
      - ${RACINE}/qbittorrent/config:/config
      - ${RACINE}/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/sonarr/config:/config
      - ${RACINE}/downloads/series:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/radarr/config:/config
      - ${RACINE}/downloads/films:/downloads
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/jackett/config:/config
      - ${RACINE}/downloads:/downloads
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/overseerr/config:/config
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${RACINE}/plex/library:/config
      - ${RACINE}/downloads/films:/films
      - ${RACINE}/downloads/series:/series
    restart: unless-stopped

networks:
  vpn-network:
    external:
      name: vpn-network
