version: "3.2"

services:
  vpn:
    image: dperson/openvpn-client:latest
    container_name: vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - label:disable
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - vpn-network
      - proxy
    dns:
      - 84.200.69.80
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - 8191:8191 # Flaresolver
      - 8586:8586 # WebUI qbittorrent
      - 9117:9117 # WebUI jackett
      - 7878:7878 # WebUI radarr
      - 8989:8989 # WebUI sonarr
      - 5055:5055 # WebUI overseer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-rtr.rule=Host(`radarr.avserver.ovh`)"
      - "traefik.http.routers.radarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.radarr-rtr.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr-rtr.tls=true"
      - "traefik.http.routers.radarr-rtr.service=radarr-svc"
      - "traefik.http.services.radarr-svc.loadbalancer.server.port=7878"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`overseerr.avserver.ovh`)"
      - "traefik.http.routers.overseerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.overseerr-rtr.tls.certresolver=myresolver"
      - "traefik.http.routers.overseerr-rtr.tls=true"
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
      - "traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.avserver.ovh`)"
      - "traefik.http.routers.sonarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.sonarr-rtr.tls.certresolver=myresolver"
      - "traefik.http.routers.sonarr-rtr.tls=true"
      - "traefik.http.routers.sonarr-rtr.service=sonarr-svc"
      - "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${RACINE}/vpn/config:/vpn
      - ${RACINE}/vpn/scripts:/scripts
    command: '-f "" -r 192.168.0.0/24'
    healthcheck:
      test: ["CMD", "curl", "-Ss", "ifconfig.me"]
      interval: 60s
      timeout: 15s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    labels:
      - autoheal=true
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8586
    volumes:
      - ${RACINE}/qbittorrent/config:/config
      - ${RACINE}/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/sonarr/config:/config
      - ${RACINE}/medias/series:/medias/series
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/radarr/config:/config
      - ${RACINE}/medias/films:/medias/films
      - ${RACINE}/downloads:/downloads
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/jackett/config:/config
      - ${RACINE}/downloads:/downloads
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RACINE}/overseerr/config:/config
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

networks:
  vpn-network:
    external:
      name: vpn-network
  proxy:
    external:
      name: proxy
